---
title: "Grade analysis"
author: "Arina Agaronyan"
format: html
code-fold: true
---

```{r config}
#| message: false
here::i_am("r-101-grade-analysis.Rproj")
library(here)
library(vroom)
library(dplyr)
library(tidyr)
library(ggplot2)
theme_set(theme_bw())
library(knitr)
library(stringr)
```

### Q1
```{r load_data}
#| message: false
grades <- vroom(here("grades.csv"))
```

### Q2
```{r exam_grades_table}
kable(grades |>
        summarise(min(Exam, na.rm=TRUE), max(Exam, na.rm=TRUE), 
                  mean(Exam, na.rm=TRUE), median(Exam, na.rm=TRUE)),
caption = "Minimum, maximum, mean and median grades of Exam", 
col.names = c("Minimum", "Maximum", "Mean", "Median"), digits = 1, align = "cccc")
```

### Q3
```{r na_exam}
n <- grades |>
  count(is.na(Exam))
```
`r n[2, 2]` students did not take the final Exam.


### Q4
```{r exam_dens}
grades|>
  filter(!is.na(Exam)) |> 
  ggplot(aes(x=Exam)) +
  geom_density()+
  labs(title = "Grade distribution of the Exam.")
```


### Q5
```{r count_group}
kable(grades |>
  group_by(Group) |>
  count(),
  caption = "Number of students in each group")
```

### Q6
```{r grp_hist}
grp_c <- grades |>
  group_by(Group) |>
  count()
grp_c |>
  ggplot(aes(x=Group, y=n)) +
  geom_col()+
  labs(title = "Number of students in each Group.")+
  guides(x = guide_axis(angle = 90))
```

### Q7
Option 1 - Facet wrap
```{r facet_exam}
grades|>
  filter(!is.na(Exam)) |> 
  ggplot(aes(x=Exam)) +
  geom_histogram(bins=20)+
  labs(title = "Grade distribution of the Exam.")+
  facet_wrap(~Group)
```

Option 2 - Boxplot
```{r box_exam}
grades|>
  filter(!is.na(Exam)) |> 
  ggplot(aes(y=Exam, x=Group)) + 
  geom_boxplot()+
  guides(x = guide_axis(angle = 90))
```


### Q8

```{r naExam-table}
grades |> 
  group_by(Group) |>
  summarise(n=sum(c(is.na(Exam))))
```


### Q9
```{r naExam-graph}
nagrades <- grades |> 
  group_by(Group) |>
  summarise(n=sum(c(is.na(Exam))))
nagrades |>
  ggplot(aes(x=Group, y=n)) +
  geom_col()+
  labs(title = "Number of students who missed Exam in each Group.")+
  guides(x = guide_axis(angle = 90))
```


### Q10

```{r IdGrpL}
IdGrpLong <- grades |>
  pivot_longer(cols = Exam:Online_MCQ_19)
```


### Q11

```{r NA/Id}
NAperId <- IdGrpLong |>
  group_by(Id) |>
  summarise(na=sum(is.na(value)))
```


### Q12
```{r NA/Id-graph}
ggplot(NAperId, aes(x=Id, y=na)) +
  geom_col()+
  labs(title = "Number of missing grades per student", x="Student Id", y="Number of missing grades")
```


### Q13
```{r NA/Grp}
IdGrpLong |> 
  group_by(Group) |>
  filter(str_starts(name, "Exam")) |>
  summarise(n=sum(c(is.na(value))))
```

### Q14

```{r OnlineNA/Id}
OnlineNA <- IdGrpLong |> 
  group_by(Id) |>
  filter(str_starts(name, "Online")) |>
  summarise("Online NA"=sum(c(is.na(value))))
```


### Q15
```{r Exam_per_OnlineNA-graph}
Exam_OnlineNA <- grades |>
  inner_join(OnlineNA, by = join_by(Id))
Exam_OnlineNA |>
  filter(!is.na(Exam)) |> 
  ggplot(aes(x=Exam))+
  geom_histogram(bins=25)+
  facet_wrap(~`Online NA`)+
  labs(title = "Exam grades distribution per number of missing online test grades")
```

### Q16

```{r MissedMCQ-Id}
kable(head(MCQ_NA <- IdGrpLong |> 
  group_by(Id) |>
  filter(str_starts(name, "MCQ")) |>
  summarise("MCQ NA"=sum(c(is.na(value)))) |>
  mutate(Missed=if_else(`MCQ NA`>0, "TRUE", "FALSE" )) |>
  select(-`MCQ NA`)), 
  caption = "First 6 rows of whether an MCQ was Missed or not per Student Id",
  align = "cc")
```



